### ISSUE TITLE
Парсинг официальных ответов на отзывы

### ISSUE THREAD

**Issue by mrkhachaturov** [useless-apple/yandex_reviews-parser#5]
Добрый день! 
Можно ли добавить в парсер официальные ответы на отзывы?

Если интересно,  можем обсудить спонсорство этого инструмента для добавления нужного функционала.

**Comment by useless-apple** [comment]
Добрый день!
Могу попробовать спарсить и ответы от организаций

**Comment by useless-apple** [comment]
https://github.com/useless-apple/yandex_reviews-parser/commit/e0145fc5ea5d2089e56dc42d517b995d2915c117
Добавил answer при парсинге
